if(NOT DEFINED CONTRACT_OUTPUT)
    message(FATAL_ERROR "CONTRACT_OUTPUT is required")
endif()

file(READ "${CONTRACT_OUTPUT}" contract)
string(REPLACE "\r" "" contract "${contract}")
string(REPLACE "\n" ";" output_lines "${contract}")

function(require_token line column length kind)
    set(found FALSE)
    foreach(output_line IN LISTS output_lines)
        string(REPLACE "\t" ";" fields "${output_line}")
        list(LENGTH fields field_count)
        if(field_count LESS 5)
            continue()
        endif()
        list(GET fields 0 record)
        list(GET fields 1 actual_line)
        list(GET fields 2 actual_column)
        list(GET fields 3 actual_length)
        list(GET fields 4 actual_kind)
        if(record STREQUAL "GSETOK"
            AND actual_line STREQUAL "${line}"
            AND actual_column STREQUAL "${column}"
            AND actual_length STREQUAL "${length}"
            AND actual_kind STREQUAL "${kind}")
            set(found TRUE)
            break()
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "Missing semantic token ${line}:${column}:${length} ${kind}")
    endif()
endfunction()

function(reject_token line column length kind)
    foreach(output_line IN LISTS output_lines)
        string(REPLACE "\t" ";" fields "${output_line}")
        list(LENGTH fields field_count)
        if(field_count LESS 5)
            continue()
        endif()
        list(GET fields 0 record)
        list(GET fields 1 actual_line)
        list(GET fields 2 actual_column)
        list(GET fields 3 actual_length)
        list(GET fields 4 actual_kind)
        if(record STREQUAL "GSETOK"
            AND actual_line STREQUAL "${line}"
            AND actual_column STREQUAL "${column}"
            AND actual_length STREQUAL "${length}"
            AND actual_kind STREQUAL "${kind}")
            message(FATAL_ERROR "Unexpected semantic token ${line}:${column}:${length} ${kind}")
        endif()
    endforeach()
endfunction()

function(require_ref line column length definition_line definition_column type)
    set(found FALSE)
    foreach(output_line IN LISTS output_lines)
        string(REPLACE "\t" ";" fields "${output_line}")
        list(LENGTH fields field_count)
        if(field_count LESS 10)
            continue()
        endif()
        list(GET fields 0 record)
        list(GET fields 2 actual_line)
        list(GET fields 3 actual_column)
        list(GET fields 4 actual_length)
        list(GET fields 7 actual_definition_line)
        list(GET fields 8 actual_definition_column)
        if(field_count GREATER 11)
            list(GET fields 11 actual_type)
        else()
            set(actual_type "")
        endif()
        if(record STREQUAL "GSEREF"
            AND actual_line STREQUAL "${line}"
            AND actual_column STREQUAL "${column}"
            AND actual_length STREQUAL "${length}"
            AND actual_definition_line STREQUAL "${definition_line}"
            AND actual_definition_column STREQUAL "${definition_column}"
            AND ("${type}" STREQUAL "" OR actual_type STREQUAL "${type}"))
            set(found TRUE)
            break()
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "Missing symbol reference ${line}:${column}:${length} -> ${definition_line}:${definition_column} type '${type}'")
    endif()
endfunction()

require_token(1 11 17 name_space)
require_token(2 9 6 type)
require_token(3 7 6 member)
require_token(6 13 6 type)
require_token(7 3 5 enum_member)
require_token(10 6 6 global)
require_token(12 4 9 attribute)
require_token(12 21 8 function)
require_token(12 38 9 parameter)
require_token(13 7 8 variable)
require_token(13 18 9 parameter)
require_token(13 28 6 member)
require_token(13 37 6 global)
require_token(14 10 8 variable)
require_token(14 21 9 parameter)
require_token(14 65 5 enum_member)
require_token(18 15 17 name_space)
require_token(18 34 8 function)
require_token(18 75 6 type)

require_ref(12 38 9 12 38 "semantic_contract::record&")
require_ref(13 7 8 13 7 "int")
require_ref(13 18 9 12 38 "semantic_contract::record&")
require_ref(13 28 6 3 7 "int")
require_ref(13 37 6 10 6 "int")
require_ref(14 10 8 13 7 "int")
require_ref(14 21 9 12 38 "semantic_contract::record&")
require_ref(14 31 6 3 7 "int")
require_ref(14 65 5 7 3 "")
require_ref(18 15 17 1 11 "")
require_ref(18 34 8 12 21 "")
require_ref(18 75 6 2 9 "")

require_token(20 8 8 type)
require_token(21 7 6 function)
require_token(21 18 9 parameter)
require_token(22 10 9 parameter)
require_token(26 6 11 function)
require_token(26 18 8 type)
require_token(26 28 5 parameter)
require_token(27 9 5 parameter)
require_token(27 15 6 function)

require_ref(21 18 9 21 18 "int")
require_ref(22 10 9 21 18 "int")
require_ref(26 28 5 26 28 "callable&")
require_ref(27 9 5 26 28 "callable&")
require_ref(27 15 6 21 7 "")

require_token(34 26 2 type)
require_token(34 29 2 member)
reject_token(34 29 2 type)
require_token(37 7 6 function)
require_token(37 14 6 type)
require_token(37 22 5 parameter)
require_token(38 10 5 parameter)
require_token(38 16 2 member)
reject_token(38 16 2 type)
