set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "" FORCE)

get_filename_component(GSE_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(GSE_ENGINE_ROOT "${GSE_SDK_ROOT}" CACHE INTERNAL "Root of the GSE engine SDK image")

file(STRINGS "${GSE_SDK_ROOT}/gse.manifest" _gse_sdk_toolchain REGEX "^toolchain = ")
string(REGEX REPLACE "^toolchain = " "" _gse_sdk_toolchain "${_gse_sdk_toolchain}")
set(_gse_sdk_toolchain_bin "$ENV{USERPROFILE}/.gcc-trunk/${_gse_sdk_toolchain}/bin")
if(NOT EXISTS "${_gse_sdk_toolchain_bin}/g++.exe")
    message(FATAL_ERROR "This SDK was built with toolchain '${_gse_sdk_toolchain}', which is not installed at ${_gse_sdk_toolchain_bin}. Install that exact release; BMIs from another compiler build fail with 'Bad file data'.")
endif()
set(CMAKE_CXX_COMPILER "${_gse_sdk_toolchain_bin}/g++.exe" CACHE FILEPATH "" FORCE)

file(STRINGS "${GSE_SDK_ROOT}/gse.manifest" _gse_sdk_build_type REGEX "^build_type = ")
string(REGEX REPLACE "^build_type = " "" _gse_sdk_build_type "${_gse_sdk_build_type}")
if(NOT _gse_sdk_build_type)
    message(FATAL_ERROR "The SDK image at ${GSE_SDK_ROOT} names no build_type in its gse.manifest.")
endif()
set(CMAKE_BUILD_TYPE "${_gse_sdk_build_type}" CACHE STRING "" FORCE)
file(TO_NATIVE_PATH "${_gse_sdk_toolchain_bin}" _gse_sdk_toolchain_bin_native)
set(ENV{PATH} "${_gse_sdk_toolchain_bin_native};$ENV{PATH}")

function(gse_configure_compiler)
    add_compile_options(-freflection -fcontracts -mavx2 -Wno-changes-meaning -Wno-error=changes-meaning)
    add_compile_options($<$<CONFIG:Release>:-fcontract-evaluation-semantic=ignore>)
    add_link_options(-fcontracts)
endfunction()

function(gse_sdk_link_modules)
    file(STRINGS "${GSE_SDK_ROOT}/gse.modules" _lines)
    foreach(_line IN LISTS _lines)
        if(_line MATCHES "^\\$")
            continue()
        endif()
        if(_line MATCHES "^[^ ]+ (.+)$")
            set(_rel "${CMAKE_MATCH_1}")
            get_filename_component(_dir "${CMAKE_BINARY_DIR}/${_rel}" DIRECTORY)
            file(MAKE_DIRECTORY "${_dir}")
            file(REMOVE "${CMAKE_BINARY_DIR}/${_rel}")
            file(CREATE_LINK "${GSE_SDK_ROOT}/${_rel}" "${CMAKE_BINARY_DIR}/${_rel}" COPY_ON_ERROR)
        endif()
    endforeach()
    file(REMOVE "${CMAKE_BINARY_DIR}/gse.modules")
    file(CREATE_LINK "${GSE_SDK_ROOT}/gse.modules" "${CMAKE_BINARY_DIR}/gse.modules" COPY_ON_ERROR)
endfunction()

function(gse_sdk_link_engine target)
    file(READ "${GSE_SDK_ROOT}/gse.link" _link)
    string(STRIP "${_link}" _link)
    separate_arguments(_items UNIX_COMMAND "${_link}")
    set(_options "")
    set(_libraries "")
    foreach(_item IN LISTS _items)
        if(_item MATCHES "^-Wl,")
            list(APPEND _options "${_item}")
        elseif(_item MATCHES "^(Engine|vcpkg_installed)/")
            list(APPEND _libraries "${GSE_SDK_ROOT}/${_item}")
        else()
            list(APPEND _libraries "${_item}")
        endif()
    endforeach()
    target_link_options(${target} PRIVATE ${_options})
    target_link_libraries(${target} PRIVATE ${_libraries})
    target_compile_options(${target} PRIVATE -fmodules-ts -fmodule-mapper=gse.modules)
    set_target_properties(${target} PROPERTIES CXX_SCAN_FOR_MODULES OFF)
endfunction()

function(gse_sdk_write_manifest)
    file(WRITE "${CMAKE_BINARY_DIR}/gse.manifest" "mode = installed\nroot = ${GSE_SDK_ROOT}\nproject = ${CMAKE_SOURCE_DIR}\n")
endfunction()

function(gse_copy_runtime_deps target)
    add_custom_command(TARGET ${target} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_directory_if_different
            "${GSE_SDK_ROOT}/Bin"
            "$<TARGET_FILE_DIR:${target}>"
    )
endfunction()
